apiVersion: v1
kind: Namespace
metadata:
  name: mreader-user
  labels:
    mreader.io/plane: user
---
apiVersion: v1
kind: Namespace
metadata:
  name: mreader-admin
  labels:
    mreader.io/plane: admin
