apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scraper-staging
  namespace: mreader-admin
  labels:
    mreader.io/plane: admin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
